import pandas as pd
import os
import glob

def process_csvs(base_directory, teams):
    """
    Processes all CSV files in the given team directories, renames columns based on predefined mappings,
    and saves the modified dataframes back to the same directories.

    Args:
        base_directory: The base directory containing team folders.
        teams: A list of team names (folder names).
    """

    # Define mappings for each CSV file (same as before)
    mappings = {
        "defense-coverage": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'PASS': 'PassRushSnaps',
            'COV': 'CoverageSnaps',
            'COV%': 'CoverageSnapsPercentage',
            'COV.1': 'CoverageGrade',
            'PEN': 'CoveragePenalties',
            'TGT': 'CoverageTargets',
            'REC': 'CoverageReceptionsAllowed',
            'REC%': 'CoverageReceptionPercentage',
            'YDS': 'CoverageYardsAllowed',
            'Y/REC': 'CoverageYardsPerReceptionAllowed',
            'YAC': 'CoverageYardsAfterCatchAllowed',
            'aDoT': 'CoverageAverageDepthOfTarget',
            'LNG': 'CoverageLongestReceptionAllowed',
            'FI': 'CoverageForcedIncompletions',
            'FI%': 'CoverageForcedIncompletionPercentage',
            'PBU': 'CoveragePassBreakups',
            'INT': 'CoverageInterceptions',
            'DRI': 'CoverageDrops',
            'TD': 'CoverageTouchdownsAllowed',
            'NFL': 'CoveragePasserRatingAllowed',
            'S/TGT': 'CoverageSnapsPerTarget',
            'S/REC': 'CoverageSnapsPerReceptionAllowed',
            'TKL': 'CoverageTackles',
            'AST': 'CoverageAssists',
            'MIS': 'CoverageMissedTackles',
            'MIS%': 'CoverageMissedTacklePercentage',
            'STOP': 'CoverageStops'
        },
        "defense-pass-rush": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'PASS': 'PassRushSnaps',
            'PRSH': 'PassRushTotalSnaps',
            'RSH%': 'PassRushSnapsPercentage',
            'PRSH.1': 'PassRushGrade',
            'PEN': 'PassRushPenalties',
            'TOT': 'PassRushTotalPressures',
            'SK': 'PassRushSacks',
            'HIT': 'PassRushHits',
            'HUR': 'PassRushHurries',
            'PRP': 'PassRushPressureRate',
            'WIN%': 'PassRushWinPercentage',
            'BAT': 'PassRushBattedPasses',
            'PASS.1': 'TruePassSetSnaps',
            'PRSH.2': 'TruePassSetTotalSnaps',
            'RSH%.1': 'TruePassSetSnapsPercentage',
            'PRSH.3': 'TruePassSetGrade',
            'TOT.1': 'TruePassSetTotalPressures',
            'SK.1': 'TruePassSetSacks',
            'HIT.1': 'TruePassSetHits',
            'HUR.1': 'TruePassSetHurries',
            'PRP.1': 'TruePassSetPressureRate',
            'WIN%.1': 'TruePassSetWinPercentage',
            'BAT.1': 'TruePassSetBattedPasses'
        },
        "defense-run": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'RDEF': 'RunDefenseSnaps',
            'RDEF.1': 'RunDefenseGrade',
            'TKL': 'RunDefenseTackles',
            'AST': 'RunDefenseAssists',
            'MIS': 'RunDefenseMissedTackles',
            'MIS%': 'RunDefenseMissedTacklePercentage',
            'STOP': 'RunDefenseStops',
            'STOP%': 'RunDefenseStopPercentage',
            'FFM': 'RunDefenseForcedFumbles',
            'AVDT': 'RunDefenseAverageDepthOfTackle',
            'PEN': 'RunDefensePenalties'
        },
        "defense": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'TOT': 'DefenseTotalSnaps',
            'RDEF': 'DefenseRunDefenseSnaps',
            'PRSH': 'DefensePassRushSnaps',
            'COV': 'DefenseCoverageSnaps',
            'DEF': 'DefenseOverallGrade',
            'RDEF.1': 'DefenseRunDefenseGrade',
            'TACK': 'DefenseTacklingGrade',
            'PRSH.1': 'DefensePassRushGrade',
            'COV.1': 'DefenseCoverageGrade',
            'TOT.1': 'DefenseTotalPressures',
            'SK': 'DefenseSacks',
            'HIT': 'DefenseHits',
            'HUR': 'DefenseHurries',
            'BAT': 'DefenseBattedPasses',
            'TKL': 'DefenseTackles',
            'AST': 'DefenseAssists',
            'MIS': 'DefenseMissedTackles',
            'MIS%': 'DefenseMissedTacklePercentage',
            'STOP': 'DefenseStops',
            'FFM': 'DefenseForcedFumbles',
            'TGT': 'DefenseTargets',
            'REC': 'DefenseReceptionsAllowed',
            'REC%': 'DefenseReceptionPercentageAllowed',
            'YDS': 'DefenseYardsAllowed',
            'Y/REC': 'DefenseYardsPerReceptionAllowed',
            'YAC': 'DefenseYardsAfterCatchAllowed',
            'LNG': 'DefenseLongestReceptionAllowed',
            'TD': 'DefenseTouchdownsAllowed',
            'INT': 'DefenseInterceptions',
            'PBU': 'DefensePassBreakups',
            'NFL': 'DefensePasserRatingAllowed',
            'PEN': 'DefensePenalties',
            'DL': 'DefenseSnapsOnDefensiveLine',
            'Box': 'DefenseSnapsInTheBox',
            'FS': 'DefenseSnapsAtFreeSafety',
            'Slot': 'DefenseSnapsInTheSlot',
            'Cnr': 'DefenseSnapsAtCorner',
            'AGP': 'DefenseSnapsAtA-Gap',
            'BGP': 'DefenseSnapsAtB-Gap',
            'OVT': 'DefenseSnapsOverTackle',
            'OUT': 'DefenseSnapsOutside'
        },
        "kick-returning": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'RETN': 'KickReturnsTotal',
            'RTN': 'KickReturnsTotalGrade',
            'KRTN': 'KickoffReturnsTotal',
            'RTN.1': 'KickoffReturnsTotalYards',
            'YDS': 'KickoffReturnsTotalYards',
            'LNG': 'KickoffReturnsLongestReturn',
            'YPA': 'KickoffReturnsYardsPerAttempt',
            'TD': 'KickoffReturnsTouchdowns',
            'FC': 'KickoffReturnsFairCatches',
            'MUF': 'KickoffReturnsMuffed',
            'PRTN': 'PuntReturnsTotal',
            'RTN.2': 'PuntReturnsTotalReturns',
            'YDS.1': 'PuntReturnsTotalYards',
            'FC.1': 'PuntReturnsTotalFairCatches',
            'LNG.1': 'PuntReturnsTotalLongestReturn',
            'YPA.1': 'PuntReturnsTotalYardsPerAttempt',
            'TD.1': 'PuntReturnsTotalTouchdowns',
            'MUF.1': 'PuntReturnsTotalMuffed'
        },
        "kicking": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'FG': 'FieldGoalGrade',
            'XP': 'ExtraPointAttempts',
            'XPA': 'ExtraPointMakes',
            'XP%': 'ExtraPointPercentage',
            'FG.1': 'FieldGoalAttempts',
            'FGA': 'FieldGoalMakes',
            'FG%': 'FieldGoalPercentage',
            'FG.2': 'FieldGoalAttempts0To19Yards',
            'FGA.1': 'FieldGoalMakes0To19Yards',
            'FG%.1': 'FieldGoalPercentage0To19Yards',
            'FG.3': 'FieldGoalAttempts20To29Yards',
            'FGA.2': 'FieldGoalMakes20To29Yards',
            'FG%.2': 'FieldGoalPercentage20To29Yards',
            'FG.4': 'FieldGoalAttempts30To39Yards',
            'FGA.3': 'FieldGoalMakes30To39Yards',
            'FG%.3': 'FieldGoalPercentage30To39Yards',
            'FG.5': 'FieldGoalAttempts40To49Yards',
            'FGA.4': 'FieldGoalMakes40To49Yards',
            'FG%.4': 'FieldGoalPercentage40To49Yards',
            'FG.6': 'FieldGoalAttempts50PlusYards',
            'FGA.5': 'FieldGoalMakes50PlusYards',
            'FG%.5': 'FieldGoalPercentage50PlusYards'
        },
        "kickoffs": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'KOFF': 'KickoffsGrade',
            'ATT': 'KickoffsTotal',
            'YPA': 'KickoffsYardsPerAttempt',
            'AFP': 'KickoffsAverageFieldPosition',
            'ONS': 'KickoffsOnsideAttempts',
            'RET%': 'KickoffsReturnPercentage',
            'RET': 'KickoffsReturned',
            'YDS': 'KickoffsYardsAllowed',
            'YPR': 'KickoffsYardsPerReturnAllowed',
            'TB': 'KickoffsTouchbacks',
            'FC': 'KickoffsFairCatches',
            'ATT.1': 'KickoffsHangtimeAverage',
            'AVG': 'KickoffsHangtimeAverage'
        },
        "offense-blocking": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'OFF': 'OffenseTotalSnaps',
            'BLK': 'BlockingTotalSnaps',
            'BLK%': 'BlockingTotalSnapsPercentage',
            'RBLK': 'RunBlockingSnaps',
            'PBLK': 'PassBlockingSnaps',
            'OFF.1': 'OffenseOverallGrade',
            'RBLK.1': 'RunBlockingGrade',
            'PBLK.1': 'PassBlockingGrade',
            'OPP': 'PressuresAllowedTotalSnaps',
            'OPP%': 'PressuresAllowedTotalSnapsPercentage',
            'SK': 'PressuresAllowedSacks',
            'HIT': 'PressuresAllowedHits',
            'HUR': 'PressuresAllowedHurries',
            'PR': 'PressuresAllowedTotal',
            'EFF': 'PressuresAllowedEfficiency',
            'PEN': 'Penalties',
            'LT': 'SnapsAtLeftTackle',
            'LG': 'SnapsAtLeftGuard',
            'C': 'SnapsAtCenter',
            'RG': 'SnapsAtRightGuard',
            'RT': 'SnapsAtRightTackle',
            'ITE': 'SnapsAtInlineTightEnd'
        },
        "offense-pass-blocking": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'PASS': 'PassBlockingTotalSnaps',
            'PBLK': 'PassBlockingTotalSnaps',
            'PB%': 'PassBlockingTotalSnapsPercentage',
            'PBLK.1': 'PassBlockingGrade',
            'PEN': 'PassBlockingPenalties',
            'OPP': 'PassBlockingPressuresAllowedTotalSnaps',
            'OPP%': 'PassBlockingPressuresAllowedTotalSnapsPercentage',
            'SK': 'PassBlockingPressuresAllowedSacks',
            'HIT': 'PassBlockingPressuresAllowedHits',
            'HUR': 'PassBlockingPressuresAllowedHurries',
            'PR': 'PassBlockingPressuresAllowedTotal',
            'EFF': 'PassBlockingPressuresAllowedEfficiency',
            'PASS.1': 'TruePassSetSnaps',
            'PBLK.2': 'TruePassSetSnaps',
            'PB%.1': 'TruePassSetSnapsPercentage',
            'PBLK.3': 'TruePassSetGrade',
            'OPP.1': 'TruePassSetPressuresAllowedTotalSnaps',
            'OPP%.1': 'TruePassSetPressuresAllowedTotalSnapsPercentage',
            'SK.1': 'TruePassSetPressuresAllowedSacks',
            'HIT.1': 'TruePassSetPressuresAllowedHits',
            'HUR.1': 'TruePassSetPressuresAllowedHurries',
            'PR.1': 'TruePassSetPressuresAllowedTotal',
            'EFF.1': 'TruePassSetPressuresAllowedEfficiency'
        },
        "offense-run-blocking": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'RUN': 'RunBlockingTotalSnaps',
            'RBLK': 'RunBlockingTotalSnaps',
            'RB%': 'RunBlockingTotalSnapsPercentage',
            'RBLK.1': 'RunBlockingGrade',
            'PEN': 'RunBlockingPenalties',
            'RBLK.2': 'RunBlockingTotalSnapsInZoneScheme',
            'SNP%': 'RunBlockingTotalSnapsInZoneSchemePercentage',
            'RBLK.3': 'RunBlockingGradeInZoneScheme',
            'RBLK.4': 'RunBlockingTotalSnapsInGapScheme',
            'SNP%.1': 'RunBlockingTotalSnapsInGapSchemePercentage',
            'RBLK.5': 'RunBlockingGradeInGapScheme'
        },
        "offense": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'TOT': 'OffenseTotalSnaps',
            'PASS': 'OffensePassingSnaps',
            'PBLK': 'OffensePassBlockingSnaps',
            'RUN': 'OffenseRushingSnaps',
            'RBLK': 'OffenseRunBlockingSnaps',
            'OFF': 'OffenseOverallGrade',
            'PASS.1': 'OffensePassingGrade',
            'PBLK.1': 'OffensePassBlockingGrade',
            'RUN.1': 'OffenseRushingGrade',
            'RBLK.1': 'OffenseRunBlockingGrade',
            'PEN': 'OffensePenalties'
        },
        "passing": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'DB': 'PassingDropbacks',
            'ATT': 'PassingAttempts',
            'COM': 'PassingCompletions',
            'COM%': 'PassingCompletionPercentage',
            'YDS': 'PassingYards',
            'YPA': 'PassingYardsPerAttempt',
            'TD': 'PassingTouchdowns',
            'INT': 'PassingInterceptions',
            'OFF': 'PassingOverallGrade',
            'PASS': 'PassingGrade',
            'RUN': 'PassingRushingGrade',
            'FUM': 'PassingFumbles',
            'BTT': 'PassingBigTimeThrows',
            'BTT%': 'PassingBigTimeThrowPercentage',
            'TWP': 'PassingTurnoverWorthyPlays',
            'TWP%': 'PassingTurnoverWorthyPlayPercentage',
            'aDoT': 'PassingAverageDepthOfTarget',
            'ADJ%': 'PassingAdjustedCompletionPercentage',
            'DRP': 'PassingDrops',
            'DRP%': 'PassingDropPercentage',
            'BAT': 'PassingBattedPasses',
            'HAT': 'PassingHitAsThrown',
            'TA': 'PassingThrowaways',
            'DPR': 'PassingDepthPercentage',
            'SK': 'PassingSacks',
            'P2S%': 'PassingPressureToSackPercentage',
            'TTT': 'PassingAverageTimeToThrow',
            'SCR': 'PassingScrambles',
            '1st': 'PassingFirstDowns',
            'NFL': 'PassingPasserRating',
            'PEN': 'PassingPenalties'
        },
        "punting": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'PUNT': 'PuntingGrade',
            'ATT': 'PuntingTotalPunts',
            'YDS': 'PuntingTotalYards',
            'YPA': 'PuntingYardsPerAttempt',
            'NET': 'PuntingNetYardsPerAttempt',
            'LNG': 'PuntingLongestPunt',
            'I20': 'PuntingInsideThe20',
            'BLK': 'PuntingBlocked',
            'RET%': 'PuntingReturnPercentage',
            'RET': 'PuntingReturned',
            'YDS.1': 'PuntingYardsAllowed',
            'YPR': 'PuntingYardsPerReturnAllowed',
            'TB': 'PuntingTouchbacks',
            'OOB': 'PuntingOutOfBounds',
            'DWN': 'PuntingDowned',
            'FC': 'PuntingFairCatches',
            'ATT.1': 'PuntingHangtimeAverage',
            'AVG': 'PuntingHangtimeAverage'
        },
        "receiving": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'TGT': 'ReceivingTargets',
            'REC': 'ReceivingReceptions',
            'REC%': 'ReceivingReceptionPercentage',
            'YDS': 'ReceivingYards',
            'Y/REC': 'ReceivingYardsPerReception',
            'TD': 'ReceivingTouchdowns',
            'OFF': 'ReceivingOverallGrade',
            'RECV': 'ReceivingGrade',
            'DROP': 'ReceivingDrops',
            'FUM': 'ReceivingFumbles',
            'PBLK': 'ReceivingPassBlockingGrade',
            'PASS': 'ReceivingPassSnaps',
            'RECV.1': 'ReceivingRoutesRun',
            'RT%': 'ReceivingTargetPercentage',
            'PBLK.1': 'ReceivingPassBlockingSnaps',
            'PB%': 'ReceivingPassBlockingSnapsPercentage',
            'SLOT': 'ReceivingSnapsInTheSlot',
            'SLT%': 'ReceivingSnapsInTheSlotPercentage',
            'WIDE': 'ReceivingSnapsWide',
            'WID%': 'ReceivingSnapsWidePercentage',
            'INL': 'ReceivingSnapsInline',
            'INL%': 'ReceivingSnapsInlinePercentage',
            'YAC': 'ReceivingYardsAfterCatch',
            'YAC/REC': 'ReceivingYardsAfterCatchPerReception',
            'Y/RR': 'ReceivingYardsPerRouteRun',
            'aDoT': 'ReceivingAverageDepthOfTarget',
            'LNG': 'ReceivingLongestReception',
            'DRP': 'ReceivingDrops',
            'DRP%': 'ReceivingDropPercentage',
            'CTT': 'ReceivingContestedTargets',
            'CTC': 'ReceivingContestedCatches',
            'CTC%': 'ReceivingContestedCatchPercentage',
            'INT': 'ReceivingInterceptionsThrownWhenTargeted',
            'FUM.1': 'ReceivingFumbles',
            'MTF': 'ReceivingMissedTacklesForced',
            '1st': 'ReceivingFirstDowns',
            'RTG': 'ReceivingPasserRatingWhenTargeted',
            'PEN': 'ReceivingPenalties'
        },
        "rushing": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'SNP': 'RushingTotalSnaps',
            'ATT': 'RushingAttempts',
            'YDS': 'RushingYards',
            'YPA': 'RushingYardsPerAttempt',
            'TD': 'RushingTouchdowns',
            'FUM': 'RushingFumbles',
            'OFF': 'RushingOverallGrade',
            'RUN': 'RushingGrade',
            'FUM.1': 'RushingFumbles',
            'RBLK': 'RushingRunBlockingGrade',
            'YCO': 'RushingYardsAfterContact',
            'YCO/A': 'RushingYardsAfterContactPerAttempt',
            'MTF': 'RushingMissedTacklesForced',
            'LNG': 'RushingLongestRush',
            '10+': 'Rushing10PlusYardRuns',
            'ZONE': 'RushingYardsInZoneScheme',
            'GAP': 'RushingYardsInGapScheme',
            'SCR': 'RushingScrambles',
            'SYDS': 'RushingScrambleYards',
            'DYDS': 'RushingDesignedYards',
            'D15+': 'Rushing15PlusYardRuns',
            'BAY': 'RushingBreakawayYards',
            'BAY%': 'RushingBreakawayPercentage',
            '1st': 'RushingFirstDowns',
            'PEN': 'RushingPenalties',
            'RECV': 'RushingReceivingGrade',
            'PBLK': 'RushingPassBlockingGrade',
            'TGT': 'RushingTargets',
            'REC': 'RushingReceptions',
            'YDS.1': 'RushingReceivingYards',
            'RSNP': 'RushingReceivingSnaps',
            'Y/RR': 'RushingYardsPerRouteRun',
            'DRP': 'RushingDrops',
            'ELU': 'RushingElusiveRating'
        },
        "schedule": {
            'WEEK': 'Week',
            '@': 'Away',
            'TEAM': 'Opponent',
            'DATE': 'Date',
            'TIME': 'Time',
            'W': 'Result',
            'PF': 'PointsFor',
            'PA': 'PointsAgainst',
            'OVER': 'OverallGrade',
            'OFF': 'OffenseGrade',
            'PASS': 'PassingGrade',
            'PBLK': 'PassBlockingGrade',
            'RECV': 'ReceivingGrade',
            'RUN': 'RushingGrade',
            'RBLK': 'RunBlockingGrade',
            'DEF': 'DefenseGrade',
            'RDEF': 'RunDefenseGrade',
            'TACK': 'TacklingGrade',
            'PRSH': 'PassRushGrade',
            'COV': 'CoverageGrade',
            'SPEC': 'SpecialTeamsGrade',
            'Unnamed: 21': 'GameReports'
        },
        "special-teams": {
            'Rank': 'Rank',
            'PLAYER': 'Player',
            '#': 'JerseyNumber',
            'POS': 'Position',
            '#G': 'GamesPlayed',
            'TOT': 'SpecialTeamsTotalSnaps',
            'KRET': 'SpecialTeamsKickReturnSnaps',
            'KCOV': 'SpecialTeamsKickCoverageSnaps',
            'PRET': 'SpecialTeamsPuntReturnSnaps',
            'PCOV': 'SpecialTeamsPuntCoverageSnaps',
            'FGBLK': 'SpecialTeamsFieldGoalBlockSnaps',
            'FGK': 'SpecialTeamsFieldGoalKickSnaps',
            'SPEC': 'SpecialTeamsOverallGrade',
            'KOFF': 'SpecialTeamsKickoffGrade',
            'PUNT': 'SpecialTeamsPuntGrade',
            'FG': 'SpecialTeamsFieldGoalGrade',
            'PEN': 'SpecialTeamsPenalties',
            'TKL': 'SpecialTeamsTackles',
            'AST': 'SpecialTeamsAssists',
            'MIS': 'SpecialTeamsMissedTackles'
        }
    }

    for team in teams:
        team_dir = os.path.join(base_directory, team)
        if os.path.isdir(team_dir):
            for filename in glob.glob(os.path.join(team_dir, "*.csv")):
                try:
                    # Extract the base filename without extension
                    base_filename = os.path.basename(filename)
                    file_parts = os.path.splitext(base_filename)[0]

                    parts = file_parts.split("_")

                    
                    category = "_".join(parts[1:])  # Join remaining parts for category

                    # Find the appropriate mapping
                    mapping = None
                    for key in mappings:
                        if key in category:
                            mapping = mappings[key]
                            break

                    if mapping:
                        # Read the CSV file into a pandas DataFrame
                        df = pd.read_csv(filename)

                        # Rename columns based on the mapping, adding category prefix
                        new_column_names = {
                            col: f"{category.upper()}_{mapping.get(col, col)}" for col in df.columns
                        }
                        df.rename(columns=new_column_names, inplace=True)

                        # Save the modified DataFrame back to CSV, replacing the original file
                        df.to_csv(filename, index=False)

                        print(f"Processed and updated: {filename}")
                    else:
                        print(f"No mapping found for: {filename}")

                except Exception as e:
                    print(f"Error processing {filename}: {e}")
        else:
            print(f"Directory not found for team: {team}")

# Example usage:
base_directory = "."  # Replace with your base directory path
teams = [
          "arizona-cardinals",
          "atlanta-falcons",
          "baltimore-ravens",
          "buffalo-bills",
          "carolina-panthers",
          "chicago-bears",
          "cincinnati-bengals",
          "cleveland-browns",
          "dallas-cowboys",
          "denver-broncos",
          "detroit-lions",
          "green-bay-packers",
          "houston-texans",
          "indianapolis-colts",
          "jacksonville-jaguars",
          "kansas-city-chiefs",
          "las-vegas-raiders",
          "los-angeles-rams",
          "los-angeles-chargers",
          "miami-dolphins",
          "minnesota-vikings",
          "new-england-patriots",
          "new-orleans-saints",
          "new-york-giants",
          "new-york-jets",
          "philadelphia-eagles",
          "pittsburgh-steelers",
          "san-francisco-49ers",
          "seattle-seahawks",
          "tampa-bay-buccaneers",
          "tennessee-titans",
          "washington-commanders"
      ]
process_csvs(base_directory, teams)